# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('data_inizio', models.DateField(verbose_name='data di inizio')),
                ('ora_inizio', models.TimeField(verbose_name='ora di inizio')),
                ('foto', models.ImageField(upload_to=b'')),
                ('prezzo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somma', models.IntegerField()),
                ('data_puntata', models.DateField(verbose_name='data puntata')),
                ('ora_puntata', models.TimeField(verbose_name='ora puntata')),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aste.Asta')),
            ],
        ),
    ]
