# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asta',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='asta',
            name='prezzo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='somma',
            field=models.FloatField(),
        ),
    ]
