# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0002_auto_20180619_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asta',
            name='ora_inizio',
        ),
        migrations.RemoveField(
            model_name='puntata',
            name='ora_puntata',
        ),
        migrations.AlterField(
            model_name='asta',
            name='data_inizio',
            field=models.DateTimeField(verbose_name='data e ora di inizio'),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='data_puntata',
            field=models.DateTimeField(verbose_name='data e ora puntata'),
        ),
    ]
