# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aste', '0004_auto_20180619_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntata',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
