# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0006_auto_20180627_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asta',
            options={'permissions': (('can_bid', 'Can Bid Auctions'),)},
        ),
    ]
