# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 14:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aste', '0007_auto_20180627_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='asta',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asta',
            name='data_inizio',
            field=models.DateTimeField(help_text='Obbligatorio.', verbose_name='data e ora di inizio'),
        ),
        migrations.AlterField(
            model_name='asta',
            name='descrizione',
            field=models.CharField(help_text='Obbligatorio.', max_length=200),
        ),
        migrations.AlterField(
            model_name='asta',
            name='foto',
            field=models.ImageField(default='default.png', help_text='Obbligatorio.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='asta',
            name='prezzo',
            field=models.FloatField(help_text='Obbligatorio.', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
