# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0009_auto_20180720_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puntata',
            unique_together=set([('asta', 'somma')]),
        ),
    ]
